version: "3.8"
services:
  ingress:
    image: opslead/swarm-ingress:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  redis:
    hostname: ingress-redis
    image: redis:7-alpine
    networks:
      - ingress
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

networks:
  ingress:
    external: true
    name: ingress