version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - ingress-routing
    deploy:
      replicas: 5 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        ingress.host: my-service.company.tld

networks:
  ingress-routing:
    external: true
    name: ingress-routing